name: Linux-next CI runner for NCM6B

on:
  push:
    branches:
      - 6tops-for-next

jobs:
  build:
    permissions: write-all
    name: linux-next ncm6b runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y gcc-9 openssl devscripts build-essential crossbuild-essential-arm64 bc bison
          sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libelf-dev libssl-dev kmod cpio libssl-dev

      - name: Clone and compile
        run: |
          mkdir out
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make defconfig 6tops-common.config
          make dtbs Image -j 16
          make modules -j 16
          sudo make modules_install INSTALL_MOD_PATH=out

      - name: Copy deb files and create archive
        run: |
          mkdir -p linux/for-next && mkdir -p dtb/rockchip && mkdir -p modules
          cp -fv arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtb* dtb/rockchip
          cp -frv arch/arm64/boot/Image dtb linux/for-next
          tar -Jcf linux.tar.xz linux
          cp -frv out/lib/modules/* modules
          tar -Jcf modules.tar.xz modules

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v2023.12-6TOPS-next-rc1"
          body: |
            ## Linux Kernel 6TOPS (for-next) rc1
            - Add linux-next support
            - Edgeble NCM6a, NCM6b
          files: |
           linux.tar.xz
           modules.tar.xz
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
